# eureka7002.hosts
# ????
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.hosts  # eureka???????
  #    server:
  #      enable-self-preservation: true  # ??????
  client:
    register-with-eureka: false  # false????????????
    fetch-registry: false  # false???????????????????
    service-url:
      # ????????eureka server ???
      # ???eureka server ??????????????????????
      defaultZone: http://eureka7001.hosts:7001/eureka/