server:
  port: 8099
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: properties
        group: DEFAULT_GROUP
  profiles:
    active: dev