## ?????
#server:
#  port: 7001
#eureka:
#  instance:
#    hostname: localhost  # eureka???????
#  server:
#    enable-self-preservation: true  # ??????
#  client:
#    register-with-eureka: false  # false????????????
#    fetch-registry: false  # false???????????????????
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # ???eureka server ??????????????????????

# eureka7001.hosts
# ????
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.hosts  # eureka???????
  #    server:
  #      enable-self-preservation: true  # ??????
  client:
    register-with-eureka: false  # false????????????
    fetch-registry: false  # false???????????????????
    service-url:
      # ????????eureka server ???
      # ???eureka server ??????????????????????
      defaultZone: http://eureka7002.hosts:7002/eureka/